---
- name: Install cPanel on a linux server
  hosts: localhost
  become: yes
  tasks: 

  - name: disable firewalld
    ansible.builtin.systemd_service:
      name: firewalld
      enabled: false
      state: stopped
    when: ansible_facts['os_family'] == "RedHat"
    #no sense in running this on debian after all

  - name: install perl
    ansible.builtin.package:
      name: 
        - perl
        - curl
      state: present
    #generic package module so this can be run on more than just rhel-based servers
    
  - name: disable SELinux
    ansible.builtin.lineinfile:
      path: /etc/selinux/config
      regex: '^SELINUX='
      line: SELINUX=disabled
    ignore_errors: true
    #if the server doesn't have SELinuix installed, I dont want the script to straight up not work

  - name: go home
    ansible.builtin.shell: cd /home
    #cPanel recommends the installation be in /home

  - name: install cPanel
    ansible.builtin.shell: curl -o latest -L https://securedownloads.cpanel.net/latest && sh latest
    #installation script taken from cPanel's documentation